-- MySQL Script generated by MySQL Workbench
-- Fri 23 Nov 2018 07:01:07 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gestorACOES
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gestorACOES` ;

-- -----------------------------------------------------
-- Schema gestorACOES
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestorACOES` DEFAULT CHARACTER SET latin1 ;
USE `gestorACOES` ;

-- -----------------------------------------------------
-- Table `gestorACOES`.`colonia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestorACOES`.`colonia` ;

CREATE TABLE IF NOT EXISTS `gestorACOES`.`colonia` (
  `id_colonia` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `numero_de_habitantes` INT(11) NOT NULL,
  `descripcion` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_colonia`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gestorACOES`.`joven`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestorACOES`.`joven` ;

CREATE TABLE IF NOT EXISTS `gestorACOES`.`joven` (
  `id_joven` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `nombre_del_padre` VARCHAR(45) NULL DEFAULT NULL,
  `nombre_de_la_madre` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `url_foto` VARCHAR(200) NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `fecha_de_alta_acoes` DATE NOT NULL,
  `fecha_de_alta` DATE NULL DEFAULT NULL,
  `fecha_de_salida_acoes` DATE NULL DEFAULT NULL,
  `grado` VARCHAR(45) NULL DEFAULT NULL,
  `historial` LONGTEXT NULL DEFAULT NULL,
  `observaciones` LONGTEXT NULL DEFAULT NULL,
  `colonia_nacimiento` INT(11) NOT NULL,
  `colonia_residencia` INT(11) NOT NULL,
  PRIMARY KEY (`id_joven`),
  INDEX `fk_joven_colonia1_idx` (`colonia_nacimiento` ASC),
  INDEX `fk_joven_colonia2_idx` (`colonia_residencia` ASC),
  CONSTRAINT `fk_joven_colonia1`
    FOREIGN KEY (`colonia_nacimiento`)
    REFERENCES `gestorACOES`.`colonia` (`id_colonia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_joven_colonia2`
    FOREIGN KEY (`colonia_residencia`)
    REFERENCES `gestorACOES`.`colonia` (`id_colonia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gestorACOES`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestorACOES`.`rol` ;

CREATE TABLE IF NOT EXISTS `gestorACOES`.`rol` (
  `rol_name` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `modificacion` TINYINT(1) NOT NULL,
  PRIMARY KEY (`rol_name`),
  UNIQUE INDEX `rol_name_UNIQUE` (`rol_name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gestorACOES`.`permiso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestorACOES`.`permiso` ;

CREATE TABLE IF NOT EXISTS `gestorACOES`.`permiso` (
  `permiso` VARCHAR(50) NOT NULL,
  `alcance` VARCHAR(45) NOT NULL,
  `descripcion_del_alcance` LONGTEXT NOT NULL,
  PRIMARY KEY (`permiso`),
  UNIQUE INDEX `permiso_UNIQUE` (`permiso` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gestorACOES`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestorACOES`.`usuario` ;

CREATE TABLE IF NOT EXISTS `gestorACOES`.`usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(16) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  `permiso` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `identificacion_UNIQUE` (`id_usuario` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  INDEX `rol_usuario_idx` (`rol` ASC),
  INDEX `fk_usuario_permiso1_idx` (`permiso` ASC),
  CONSTRAINT `rol_usuario`
    FOREIGN KEY (`rol`)
    REFERENCES `gestorACOES`.`rol` (`rol_name`),
  CONSTRAINT `fk_usuario_permiso1`
    FOREIGN KEY (`permiso`)
    REFERENCES `gestorACOES`.`permiso` (`permiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gestorACOES`.`socio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestorACOES`.`socio` ;

CREATE TABLE IF NOT EXISTS `gestorACOES`.`socio` (
  `id_socio` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `poblacion` VARCHAR(45) NULL DEFAULT NULL,
  `codigo_postal` VARCHAR(45) NULL DEFAULT NULL,
  `provincia` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `telefono1` VARCHAR(45) NULL DEFAULT NULL,
  `telefono2` VARCHAR(45) NULL DEFAULT NULL,
  `correo_electronico` VARCHAR(45) NULL DEFAULT NULL,
  `relacion` VARCHAR(45) NULL DEFAULT NULL,
  `certificado` TINYINT(4) NULL DEFAULT NULL,
  `sector` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_de_alta` DATE NOT NULL,
  `fecha_de_baja` DATE NULL DEFAULT NULL,
  `observaciones` LONGTEXT NULL DEFAULT NULL,
  `usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_socio`),
  INDEX `fk_socio_usuario1_idx` (`usuario` ASC),
  CONSTRAINT `fk_socio_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `gestorACOES`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gestorACOES`.`voluntario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestorACOES`.`voluntario` ;

CREATE TABLE IF NOT EXISTS `gestorACOES`.`voluntario` (
  `id_voluntario` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `fecha_alta` DATE NOT NULL,
  `correo_electronico` VARCHAR(45) NULL DEFAULT NULL,
  `telefono_contacto` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `codigo_postal` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_voluntario`),
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC),
  INDEX `fk_voluntario_usuario1_idx` (`usuario` ASC),
  CONSTRAINT `fk_voluntario_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `gestorACOES`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gestorACOES`.`apadrinamiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestorACOES`.`apadrinamiento` ;

CREATE TABLE IF NOT EXISTS `gestorACOES`.`apadrinamiento` (
  `idApadrinamiento` INT(11) NOT NULL,
  `fecha_de_inicio` DATE NOT NULL,
  `fecha_de_baja` DATE NULL DEFAULT NULL,
  `socio` INT(11) NOT NULL,
  `voluntario` INT(11) NOT NULL,
  `joven` INT(11) NOT NULL,
  PRIMARY KEY (`idApadrinamiento`),
  UNIQUE INDEX `idApadrinamiento_UNIQUE` (`idApadrinamiento` ASC),
  INDEX `fk_apadrinamiento_socio1_idx` (`socio` ASC),
  INDEX `fk_apadrinamiento_voluntario1_idx` (`voluntario` ASC),
  INDEX `fk_apadrinamiento_joven1_idx` (`joven` ASC),
  CONSTRAINT `fk_apadrinamiento_joven1`
    FOREIGN KEY (`joven`)
    REFERENCES `gestorACOES`.`joven` (`id_joven`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_apadrinamiento_socio1`
    FOREIGN KEY (`socio`)
    REFERENCES `gestorACOES`.`socio` (`id_socio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_apadrinamiento_voluntario1`
    FOREIGN KEY (`voluntario`)
    REFERENCES `gestorACOES`.`voluntario` (`id_voluntario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gestorACOES`.`envios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestorACOES`.`envios` ;

CREATE TABLE IF NOT EXISTS `gestorACOES`.`envios` (
  `id_envios` INT(11) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `eviado_por_socio` TINYINT(1) NULL DEFAULT NULL,
  `recibido` TINYINT(1) NULL DEFAULT NULL,
  `respuestaA` INT(11) NULL DEFAULT NULL,
  `apadrinamiento` INT(11) NOT NULL,
  PRIMARY KEY (`id_envios`),
  INDEX `fk_envios_envios1_idx` (`respuestaA` ASC),
  INDEX `fk_envios_apadrinamiento1_idx` (`apadrinamiento` ASC),
  CONSTRAINT `fk_envios_apadrinamiento1`
    FOREIGN KEY (`apadrinamiento`)
    REFERENCES `gestorACOES`.`apadrinamiento` (`idApadrinamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_envios_envios1`
    FOREIGN KEY (`respuestaA`)
    REFERENCES `gestorACOES`.`envios` (`id_envios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gestorACOES`.`proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestorACOES`.`proyecto` ;

CREATE TABLE IF NOT EXISTS `gestorACOES`.`proyecto` (
  `id_proyecto` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `requisitos_participacion` LONGTEXT NULL DEFAULT NULL,
  `descripcion` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_proyecto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gestorACOES`.`pertenecer_proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestorACOES`.`pertenecer_proyecto` ;

CREATE TABLE IF NOT EXISTS `gestorACOES`.`pertenecer_proyecto` (
  `joven` INT(11) NOT NULL,
  `proyecto` INT(11) NOT NULL,
  `fecha_de_alta` DATE NOT NULL,
  `fecha_de_baja` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`joven`, `proyecto`),
  INDEX `fk_joven_has_proyecto_proyecto1_idx` (`proyecto` ASC),
  INDEX `fk_joven_has_proyecto_joven1_idx` (`joven` ASC),
  CONSTRAINT `fk_joven_has_proyecto_joven1`
    FOREIGN KEY (`joven`)
    REFERENCES `gestorACOES`.`joven` (`id_joven`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_joven_has_proyecto_proyecto1`
    FOREIGN KEY (`proyecto`)
    REFERENCES `gestorACOES`.`proyecto` (`id_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gestorACOES`.`transaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestorACOES`.`transaccion` ;

CREATE TABLE IF NOT EXISTS `gestorACOES`.`transaccion` (
  `id_transaccion` INT(11) NOT NULL,
  `gasto` TINYINT(1) NOT NULL,
  `fechaEmision` DATE NOT NULL,
  `cuantia` INT(11) NOT NULL,
  `moneda` VARCHAR(45) NOT NULL,
  `destino` VARCHAR(45) NULL DEFAULT NULL,
  `formaDePago` VARCHAR(45) NULL DEFAULT NULL,
  `motivo` VARCHAR(45) NULL DEFAULT NULL,
  `proyecto` INT(11) NULL DEFAULT NULL,
  `apadrinamiento` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_transaccion`),
  INDEX `fk_transaccion_proyecto1_idx` (`proyecto` ASC),
  INDEX `fk_transaccion_apadrinamiento1_idx` (`apadrinamiento` ASC),
  CONSTRAINT `fk_transaccion_apadrinamiento1`
    FOREIGN KEY (`apadrinamiento`)
    REFERENCES `gestorACOES`.`apadrinamiento` (`idApadrinamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaccion_proyecto1`
    FOREIGN KEY (`proyecto`)
    REFERENCES `gestorACOES`.`proyecto` (`id_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
